name: Auto Assigner
on: [pull_request]

jobs:
  autoassign:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - uses: toshimaru/auto-author-assign@v2.1.1
